[DEV-26] soft-delete 설정 및 flyway 적용
COW-dev/ddingdong-be pull request #76
Opened 2024-08-15 13:41 UTC by KoSeonJe

## 🚀 작업 내용
1. 모든 entity에 대해 soft-delete 적용했습니다.
2. flyway 적용하였습니다.
3. isDeleted 컬럼 추가 스크립트 작성하였습니다.

## 🤔 고민했던 내용
- 모든 엔터티에 soft delete 적용하는게 맞는 것인가 고민하였습니다. 너무 공간 낭비가 될 것이라 생각하지만, 저희 도메인 특성상 그렇게 데이터가 많이 추가되지 않을 것 같아서.. 일단 전부 적용 하였습니다.
- deleted 컬럼을 boolean으로 해야하는지 timestamp로 삭제시간을 저장해야할 지 고민하였습니다. 많은 부분에서 후자로 적용하고, 완전 삭제를 추후에 한다던데, 완전 삭제 로직을 추가로 짜야해서 정해야 할 것 같습니다.
- 사실 flyway 로컬에서 테스트 해보고싶었는데, mysql pr이 머지가 안되서 아직 못했습니다..

그리고 flyway 스크립트에 컨벤션이 있답니다.
[버전][버전번호]_[description].sql
## 💬 리뷰 중점사항
- deleted 컬럼 boolean으로 할지 timestamp로 할지?
- 모든 entity soft-deleted??

2024-08-15 16:21 UTC, 5uhwann requested changes
soft delete는 지난번 회의 때 이야기 나온 도메인들만 우선 적용해도 괜찮을거 같습니다!
그리고 soft delete 방식은 timestamp 방식이 좋을 거 같네요!

2024-08-15 16:21 UTC, 5uhwann commented on src/main/resources/db/migration/V1_Add_softdelete_column.sql
> +ALTER TABLE activity_report ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
p1)
flyway 마이그레이션 스크립트 파일 컨벤션에서 버전명과 description 사이의 언더스코어 2개입니다!
ex. V1__Add_softdelete_column.sql

추가로 정확하진 않지만 마이그레이션을 진행할 베이스라인이 있을 경우 V1의 초기 파일에는 빈 스크립트를 작성했던 것 같은데 추후 로컬에서 테스트 후 확인바랍니다!

2024-08-15 17:18 UTC, KoSeonJe commented on src/main/resources/db/migration/V1_Add_softdelete_column.sql
> +ALTER TABLE activity_report ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
아 왠지 안되더라고요... 감사합니다

2024-08-15 17:58 UTC, KoSeonJe commented on src/main/resources/db/migration/V1_Add_softdelete_column.sql
> +ALTER TABLE activity_report ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
수정 완료하였습니다.

2024-08-16 09:22 UTC, 5uhwann approved these changes
고생하셨습니다~

2024-08-16 09:24 UTC, wonjunYou approved these changes
리뷰가 늦었네요..! 고생하셨습니다 ㅎㅎ

2024-08-18 03:15 UTC, wonjunYou commented
홀리 깜짝놀랐네요 ..ㅋㅋㅋㅋ

2024-08-21 09:41 UTC, merged