[DEV-43] 동아리 게시물 CRUD 및 Feed 조회 API
COW-dev/ddingdong-be pull request #87
Opened 2024-08-28 09:33 UTC by KoSeonJe

## 🚀 작업 내용
- 동아리 게시물 CRUD
- Feed 조회 API

## 🤔 고민했던 내용
- FacadeService에 @Transactional을 선언해야 할지 하위 서비스에 선언해야할 지 고민했습니다.
일단, 작은 단위의 트랜잭션이 좋다고 하여 하위 서비스에 선언하였습니다.

- 최신순으로 동아리 게시물 조회, 각 동아리별 최신 게시물 1개를 모두 조회하는 피드 조회를 JPQL로 일단 작성하였는데, 필요하다면 QueryDSL로 변경해도 될 것 같습니다. 혹은 다른 방법이 더 효율적이라면 방법을 바꾸겠습니다.

- 이미지 혹은 동영상 URL을 받아오고, 내보내는데, 모두 URL로 다뤘는데 잘 못된점 있다면 피드백 바랍니다.

## 💬 리뷰 중점사항
- 위 고민 내용! 중심으로 봐주시면 감사하겠습니다

* 아직 테스트는 작성중이라 후에 올리겠습니다

2024-08-28 14:08 UTC, wonjunYou requested changes
고생하셨습니다~

2024-08-28 14:08 UTC, wonjunYou commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/repository/ClubPostRepository.java
> +      + "SELECT MAX(p2.created_at)"
p3) 이거 생성 시각도 좋지만 id로 잡는게 더 좋을 것 같아요

pk에 클러스터링 인덱스가 걸리게 되므로 기본적으로 id값을 기준으로 이미 정렬이 되어 있을 테니 역순 정렬시에도 인덱스 기준으로 정렬하게 될 거라 훨씬 효율적일거에요

또한 집계함수 쓰게 되면 인덱스를 태울 수가 없고 무조건 풀스캔이라 아래와 같은 쿼리로 가면 좋을 것 같습니다~

SELECT id 
FROM club_post cp
WHERE cp.club_id = p.club_id)
ORDER BY id desc
LIMIT 1

2024-08-28 14:08 UTC, wonjunYou commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/repository/ClubPostRepository.java
> +  List<ClubPost> findAllByClubIdOrderByCreatedAt(@Param("clubId") Long clubId);
p3) 이것도 아래와 같은 맥락에서 order by를 id로 걸면 더 효율적일 것 같아요

2024-08-28 14:08 UTC, wonjunYou commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +  public ClubPostListResponse getRecentAllByClubId(Long clubId) {
p3) recent라는 네이밍이 들어갔을 때 직관적으로 잘 와닿지 않는 것 같아요..! 최근것을 기준으로 필터링되는건가..? 라는 생각이 먼저 들었습니다!

2024-08-28 14:08 UTC, wonjunYou commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostService.java
> +        .orElseThrow(() -> new ResourceNotFound("존재하지 않은 동아리 게시물입니다."));
p4)
```suggestion
        .orElseThrow(() -> new ResourceNotFound("존재하지 않는 동아리 게시물입니다."));
```

2024-08-28 14:08 UTC, wonjunYou commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/dto/CreateClubPostCommand.java
> +package ddingdong.ddingdongBE.domain.clubpost.service.dto;
p4) 오호 결국 dto를 두번 만들어 나가는건가요??

2024-08-28 16:08 UTC, 5uhwann commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/api/ClubPostAPI.java
> +  @GetMapping("/{clubId}")
p3) 제 생각에도 server/club/{clubId}/posts가 더 자연스러운거 같습니다

2024-08-28 16:10 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/api/ClubPostAPI.java
> +public interface ClubPostAPI {
아 감사합니다 수정하겠습니다

2024-08-28 16:11 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/api/ClubPostAPI.java
> +@Tag(name = "Club - Post", description = "Club Post API")
수정하겠습니다!

2024-08-28 16:14 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/api/ClubPostAPI.java
> +@Tag(name = "Club - Post", description = "Club Post API")
아 숙지하지 못했습니다 수정하겠습니다

2024-08-28 16:15 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/api/ClubPostAPI.java
> +  @GetMapping("/{clubId}")
아 생각없이 했나 봅니다 감사합니다 수정하겠습니다

2024-08-28 16:24 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/entity/ClubPost.java
> +  }
아 저는 연관관계 주입을 엔터티 생성과 동시에 하는 것보다 따로 관리하는 게 더 좋다고 느껴져서 그랬습니다.
하나로 합치는게 더 좋을까요?

2024-08-28 16:28 UTC, 5uhwann requested changes
고생하셨습니다~
파일 업로드 관련 로직은 이후 작업될 Club 도메인에 적용될 내용 확인 후 해당 코드 참고하여 추가 적용 부탁드립니다!

2024-08-28 16:28 UTC, 5uhwann commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/controller/dto/request/ClubFeedResponse.java
> +package ddingdong.ddingdongBE.domain.clubpost.controller.dto.request;
p2) 패키지 위치 확인해주세요!
```suggestion
package ddingdong.ddingdongBE.domain.clubpost.controller.dto.response;
```

2024-08-28 16:28 UTC, 5uhwann commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/controller/dto/request/ClubFeedResponse.java
> +public record ClubFeedResponse(
p3) 해당 부분도 명세 추가 부탁드립니다!

2024-08-28 16:28 UTC, 5uhwann commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/entity/ClubPost.java
> +  }
p4) 빌더 생성자가 있는데 팩토리 메서드를 사용하는 이유가 따로 있나요??

2024-08-28 16:28 UTC, 5uhwann commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +    clubPostService.create(club, command);
p3) 해당 단계에서 ClubPost Entity를 만들어서 ClubPostService에는Entity만 넘기는게 좋을듯 싶습니다.

2024-08-28 16:28 UTC, 5uhwann commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +    clubPostService.update(command);
p3) create과 마찬가지로 Entity로 지금 단계에서 entity 변환을 마치는게 좋을거 같습니다!

2024-08-28 16:28 UTC, 5uhwann commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +  public ClubPostListResponse getRecentAllByClubId(Long clubId) {
getNewestAllByClubId는 어떨까요..?

2024-08-28 18:01 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +  public ClubPostListResponse getRecentAllByClubId(Long clubId) {
사실 동아리 게시물 모두 조회해오는거라, 그냥 getAllByClubId로 하고,
동아리 피드가 최신 게시물만 불러오는거라 Newest 붙이는것은 어떤가요?

2024-08-28 18:03 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/entity/ClubPost.java
> +  }
서비스 메소드에 builder를 사용하면 가독성을 해칠까봐 작성하였습니다. 그냥 서비스 메소드 내에 builder사용해서 생성하는 것이 좋아보이나요?

2024-08-28 18:09 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +    clubPostService.create(club, command);
아 그렇다면, 메소드명을 create -> save로 바꾸겠습니다

2024-08-28 18:10 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/entity/ClubPost.java
> +  }
아.. 제가 헷갈렸네요 필요 없을 것 같습니다 삭제 하겠습니다

2024-08-28 18:16 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +    clubPostService.update(command);
근데 클래스 간의 데이터를 주고받을때 DTO를 사용하는 게 좋지 않나요?? 엔터티를 직접 주고받으면 안좋은 것 같아서. 괜찮다고 생각하시는 편인가요?

2024-08-28 20:34 UTC, 5uhwann commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +    clubPostService.update(command);
기본 도메인 서비스 클래스 자체가 별도의 비즈니스 로직 없이 해당 도메인에 대한 CRUD만 책임지고 있기 때문에 엔티티를 사용하는 것이 괜찮다는 입장이긴 합니다!
그리고 return은 전부 엔티티로 하는데 파라미터가 엔티티로 안되는게 크게 의미가 없을거 같긴 합니다..ㅎ

2024-08-28 20:58 UTC, KoSeonJe commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +    clubPostService.update(command);
네 알겠습니다!
근데 이 업데이트는 직접 엔터티를 넘기면 그 엔터티가 업데이트 정보를 갖고있고, 업데이트할 postid도 같이 넘기면 매개변수 2개가 되는 경우가 있고
아니면, 그냥 FacadeService에서 직접 entity 조회해서 업데이트 해줘야하는데
위 두 경우가 나을까요 아니면 지금 그대로가 나을까요

2024-08-28 23:28 UTC, wonjunYou commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +  public ClubPostListResponse getRecentAllByClubId(Long clubId) {
아 최신 게시물만 필터링해서 불러오는 메서드 맞으면 저렇게 가도 될 것 같습니다 ㅎㅎㅎㅎ

2024-08-29 02:03 UTC, wonjunYou commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/entity/ClubPost.java
> +  }
그런 측면에서는 좋은 방법이지만, 한편으로는 특정 domain service에서 연관 도메인의 entity를 의존하게 되는 구조가 되어버리는 것 같다는 생각이 들어서요..!

2024-08-30 07:29 UTC, wonjunYou commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/api/ClubPostAPI.java
> +@RequestMapping("/server/club/posts")
둘다 괜찮은 것 같아요! 저라면 url을 변경하는 쪽을 택할 것 같습니다

2024-08-30 07:34 UTC, wonjunYou commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +    clubPostService.update(command);
음.. 이거 제 생각에는 우선 dto를 domain service까지 굳이 끌고 갈 필요는 없다는 생각이 듭니다!

클래스 간에 dto를 사용한다기보다 서로 다른 계층(layer)간에 dto 사용을 권장한다는 표현이 맞을 것 같아요

도메인 서비스에서는 최대한 엔티티 변환이 가능한 요소라면 변환을 하는 게 좋을 것 같아요

사실 굳이 완성된 entity를 넘길 필요는 없고 만약 뭐 id만 넘겨야 한다 이러면 id를 넘기고 실제 조회는 domain service에서 하는 게적합한 구조인 것 같아요

2024-08-30 07:34 UTC, wonjunYou commented on src/main/java/ddingdong/ddingdongBE/domain/clubpost/service/ClubPostFacadeService.java
> +    clubPostService.update(command);
선제님이 마지막에 말씀주신 내용이 잘 이해가 가지 않아서, 혹시 좀 더 부연설명 가능할까요??

2024-08-31 11:44 UTC, closed without merging